"""add execution idempotency key

Revision ID: 2f63ab0f6a5c
Revises: 9074fc8b7cf6
Create Date: 2026-09-05 21:16:31.207073

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f63ab0f6a5c'
down_revision: Union[str, Sequence[str], None] = '9074fc8b7cf6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('idempotency_key', sa.String(length=128), nullable=True))
    op.create_unique_constraint('uq_tasks_investigation_idempotency_key', 'tasks', ['investigation_id', 'idempotency_key'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_tasks_investigation_idempotency_key', 'tasks', type_='unique')
    op.drop_column('tasks', 'idempotency_key')
    # ### end Alembic commands ###
