"""add image geospatial metadata

Revision ID: 61916fe6f885
Revises: de762670861d
Create Date: 2026-09-05 20:19:20.372250

"""
from typing import Sequence, Union

from alembic import op
import geoalchemy2
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '61916fe6f885'
down_revision: Union[str, Sequence[str], None] = 'de762670861d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('image_metadata', sa.Column('footprint_geometry', geoalchemy2.types.Geometry(geometry_type='POLYGON', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True))
    op.add_column('image_metadata', sa.Column('bounding_geometry', geoalchemy2.types.Geometry(geometry_type='POLYGON', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True))
    op.add_column('image_metadata', sa.Column('centroid_geometry', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('image_metadata', 'centroid_geometry')
    op.drop_column('image_metadata', 'bounding_geometry')
    op.drop_column('image_metadata', 'footprint_geometry')
    # ### end Alembic commands ###
