"""create initial relational model

Revision ID: de762670861d
Revises: 
Create Date: 2026-09-05 20:16:53.870875

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de762670861d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index('ix_users_created_at', 'users', ['created_at'], unique=False)
    op.create_table('projects',
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=2000), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_projects_owner_created_at', 'projects', ['owner_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_projects_owner_id'), 'projects', ['owner_id'], unique=False)
    op.create_table('investigations',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('planned', 'running', 'complete', 'blocked', name='investigation_status'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_investigations_project_created_at', 'investigations', ['project_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_investigations_project_id'), 'investigations', ['project_id'], unique=False)
    op.create_index('ix_investigations_status_updated_at', 'investigations', ['status', 'updated_at'], unique=False)
    op.create_table('hypotheses',
    sa.Column('investigation_id', sa.Uuid(), nullable=False),
    sa.Column('statement', sa.Text(), nullable=False),
    sa.Column('assessment_state', sa.Enum('proposed', 'under_review', 'supported', 'rejected', 'inconclusive', name='assessment_state'), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_hypotheses_created_at', 'hypotheses', ['created_at'], unique=False)
    op.create_index(op.f('ix_hypotheses_investigation_id'), 'hypotheses', ['investigation_id'], unique=False)
    op.create_index('ix_hypotheses_investigation_state', 'hypotheses', ['investigation_id', 'assessment_state'], unique=False)
    op.create_table('queries',
    sa.Column('investigation_id', sa.Uuid(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_queries_investigation_created_at', 'queries', ['investigation_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_queries_investigation_id'), 'queries', ['investigation_id'], unique=False)
    op.create_table('tasks',
    sa.Column('investigation_id', sa.Uuid(), nullable=False),
    sa.Column('task_type', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('pending', 'running', 'succeeded', 'failed', 'cancelled', name='execution_status'), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_tasks_created_at', 'tasks', ['created_at'], unique=False)
    op.create_index(op.f('ix_tasks_investigation_id'), 'tasks', ['investigation_id'], unique=False)
    op.create_index('ix_tasks_investigation_status', 'tasks', ['investigation_id', 'status'], unique=False)
    op.create_table('uploaded_images',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('investigation_id', sa.Uuid(), nullable=False),
    sa.Column('original_filename', sa.String(length=1024), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_uploaded_images_investigation_created_at', 'uploaded_images', ['investigation_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_uploaded_images_investigation_id'), 'uploaded_images', ['investigation_id'], unique=False)
    op.create_index('ix_uploaded_images_project_created_at', 'uploaded_images', ['project_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_uploaded_images_project_id'), 'uploaded_images', ['project_id'], unique=False)
    op.create_table('conclusions',
    sa.Column('investigation_id', sa.Uuid(), nullable=False),
    sa.Column('hypothesis_id', sa.Uuid(), nullable=True),
    sa.Column('state', sa.Enum('draft', 'final', 'inconclusive', name='conclusion_state'), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('rationale', sa.JSON(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['hypothesis_id'], ['hypotheses.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_conclusions_created_at', 'conclusions', ['created_at'], unique=False)
    op.create_index(op.f('ix_conclusions_hypothesis_id'), 'conclusions', ['hypothesis_id'], unique=False)
    op.create_index(op.f('ix_conclusions_investigation_id'), 'conclusions', ['investigation_id'], unique=False)
    op.create_index('ix_conclusions_investigation_state', 'conclusions', ['investigation_id', 'state'], unique=False)
    op.create_table('image_metadata',
    sa.Column('image_id', sa.Uuid(), nullable=False),
    sa.Column('modality', sa.Enum('optical', 'multispectral', 'sar', name='image_modality'), nullable=False),
    sa.Column('acquisition_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('crs', sa.String(length=255), nullable=True),
    sa.Column('bounding_box', sa.JSON(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('band_information', sa.JSON(), nullable=True),
    sa.Column('file_format', sa.String(length=100), nullable=True),
    sa.Column('mime_type', sa.String(length=255), nullable=True),
    sa.Column('checksum', sa.String(length=255), nullable=True),
    sa.Column('storage_location', sa.String(length=2048), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['image_id'], ['uploaded_images.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('image_id')
    )
    op.create_index(op.f('ix_image_metadata_acquisition_at'), 'image_metadata', ['acquisition_at'], unique=False)
    op.create_index(op.f('ix_image_metadata_checksum'), 'image_metadata', ['checksum'], unique=False)
    op.create_index('ix_image_metadata_modality_acquisition', 'image_metadata', ['modality', 'acquisition_at'], unique=False)
    op.create_table('image_relationships',
    sa.Column('source_image_id', sa.Uuid(), nullable=False),
    sa.Column('related_image_id', sa.Uuid(), nullable=False),
    sa.Column('relationship_type', sa.Enum('bi_temporal', 'cross_modal', name='image_relationship_type'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('source_image_id <> related_image_id', name='ck_image_relationship_distinct_images'),
    sa.ForeignKeyConstraint(['related_image_id'], ['uploaded_images.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_image_id'], ['uploaded_images.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_image_relationships_related_image_id'), 'image_relationships', ['related_image_id'], unique=False)
    op.create_index(op.f('ix_image_relationships_source_image_id'), 'image_relationships', ['source_image_id'], unique=False)
    op.create_index('ix_image_relationships_type_created_at', 'image_relationships', ['relationship_type', 'created_at'], unique=False)
    op.create_table('model_runs',
    sa.Column('task_id', sa.Uuid(), nullable=False),
    sa.Column('model_name', sa.String(length=255), nullable=False),
    sa.Column('model_version', sa.String(length=255), nullable=True),
    sa.Column('tool_name', sa.String(length=255), nullable=True),
    sa.Column('parameters', sa.JSON(), nullable=True),
    sa.Column('input_ids', sa.JSON(), nullable=True),
    sa.Column('output_metadata', sa.JSON(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'running', 'succeeded', 'failed', 'cancelled', name='execution_status'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_information', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_model_runs_started_at', 'model_runs', ['started_at'], unique=False)
    op.create_index(op.f('ix_model_runs_task_id'), 'model_runs', ['task_id'], unique=False)
    op.create_index('ix_model_runs_task_status', 'model_runs', ['task_id', 'status'], unique=False)
    op.create_table('evidence',
    sa.Column('investigation_id', sa.Uuid(), nullable=False),
    sa.Column('hypothesis_id', sa.Uuid(), nullable=True),
    sa.Column('image_id', sa.Uuid(), nullable=True),
    sa.Column('query_id', sa.Uuid(), nullable=True),
    sa.Column('model_run_id', sa.Uuid(), nullable=True),
    sa.Column('polarity', sa.Enum('supporting', 'contradicting', 'neutral', 'insufficient', name='evidence_polarity'), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('provenance', sa.JSON(), nullable=False),
    sa.Column('source_uri', sa.String(length=2048), nullable=True),
    sa.Column('source_reference', sa.String(length=1024), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['hypothesis_id'], ['hypotheses.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['image_id'], ['uploaded_images.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['model_run_id'], ['model_runs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['query_id'], ['queries.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_evidence_created_at', 'evidence', ['created_at'], unique=False)
    op.create_index(op.f('ix_evidence_hypothesis_id'), 'evidence', ['hypothesis_id'], unique=False)
    op.create_index(op.f('ix_evidence_image_id'), 'evidence', ['image_id'], unique=False)
    op.create_index(op.f('ix_evidence_investigation_id'), 'evidence', ['investigation_id'], unique=False)
    op.create_index('ix_evidence_investigation_polarity', 'evidence', ['investigation_id', 'polarity'], unique=False)
    op.create_index(op.f('ix_evidence_model_run_id'), 'evidence', ['model_run_id'], unique=False)
    op.create_index(op.f('ix_evidence_query_id'), 'evidence', ['query_id'], unique=False)
    op.create_table('reports',
    sa.Column('investigation_id', sa.Uuid(), nullable=False),
    sa.Column('conclusion_id', sa.Uuid(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('storage_location', sa.String(length=2048), nullable=True),
    sa.Column('checksum', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conclusion_id'], ['conclusions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reports_checksum'), 'reports', ['checksum'], unique=False)
    op.create_index(op.f('ix_reports_conclusion_id'), 'reports', ['conclusion_id'], unique=False)
    op.create_index('ix_reports_investigation_created_at', 'reports', ['investigation_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_reports_investigation_id'), 'reports', ['investigation_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reports_investigation_id'), table_name='reports')
    op.drop_index('ix_reports_investigation_created_at', table_name='reports')
    op.drop_index(op.f('ix_reports_conclusion_id'), table_name='reports')
    op.drop_index(op.f('ix_reports_checksum'), table_name='reports')
    op.drop_table('reports')
    op.drop_index(op.f('ix_evidence_query_id'), table_name='evidence')
    op.drop_index(op.f('ix_evidence_model_run_id'), table_name='evidence')
    op.drop_index('ix_evidence_investigation_polarity', table_name='evidence')
    op.drop_index(op.f('ix_evidence_investigation_id'), table_name='evidence')
    op.drop_index(op.f('ix_evidence_image_id'), table_name='evidence')
    op.drop_index(op.f('ix_evidence_hypothesis_id'), table_name='evidence')
    op.drop_index('ix_evidence_created_at', table_name='evidence')
    op.drop_table('evidence')
    op.drop_index('ix_model_runs_task_status', table_name='model_runs')
    op.drop_index(op.f('ix_model_runs_task_id'), table_name='model_runs')
    op.drop_index('ix_model_runs_started_at', table_name='model_runs')
    op.drop_table('model_runs')
    op.drop_index('ix_image_relationships_type_created_at', table_name='image_relationships')
    op.drop_index(op.f('ix_image_relationships_source_image_id'), table_name='image_relationships')
    op.drop_index(op.f('ix_image_relationships_related_image_id'), table_name='image_relationships')
    op.drop_table('image_relationships')
    op.drop_index('ix_image_metadata_modality_acquisition', table_name='image_metadata')
    op.drop_index(op.f('ix_image_metadata_checksum'), table_name='image_metadata')
    op.drop_index(op.f('ix_image_metadata_acquisition_at'), table_name='image_metadata')
    op.drop_table('image_metadata')
    op.drop_index('ix_conclusions_investigation_state', table_name='conclusions')
    op.drop_index(op.f('ix_conclusions_investigation_id'), table_name='conclusions')
    op.drop_index(op.f('ix_conclusions_hypothesis_id'), table_name='conclusions')
    op.drop_index('ix_conclusions_created_at', table_name='conclusions')
    op.drop_table('conclusions')
    op.drop_index(op.f('ix_uploaded_images_project_id'), table_name='uploaded_images')
    op.drop_index('ix_uploaded_images_project_created_at', table_name='uploaded_images')
    op.drop_index(op.f('ix_uploaded_images_investigation_id'), table_name='uploaded_images')
    op.drop_index('ix_uploaded_images_investigation_created_at', table_name='uploaded_images')
    op.drop_table('uploaded_images')
    op.drop_index('ix_tasks_investigation_status', table_name='tasks')
    op.drop_index(op.f('ix_tasks_investigation_id'), table_name='tasks')
    op.drop_index('ix_tasks_created_at', table_name='tasks')
    op.drop_table('tasks')
    op.drop_index(op.f('ix_queries_investigation_id'), table_name='queries')
    op.drop_index('ix_queries_investigation_created_at', table_name='queries')
    op.drop_table('queries')
    op.drop_index('ix_hypotheses_investigation_state', table_name='hypotheses')
    op.drop_index(op.f('ix_hypotheses_investigation_id'), table_name='hypotheses')
    op.drop_index('ix_hypotheses_created_at', table_name='hypotheses')
    op.drop_table('hypotheses')
    op.drop_index('ix_investigations_status_updated_at', table_name='investigations')
    op.drop_index(op.f('ix_investigations_project_id'), table_name='investigations')
    op.drop_index('ix_investigations_project_created_at', table_name='investigations')
    op.drop_table('investigations')
    op.drop_index(op.f('ix_projects_owner_id'), table_name='projects')
    op.drop_index('ix_projects_owner_created_at', table_name='projects')
    op.drop_table('projects')
    op.drop_index('ix_users_created_at', table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
